global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-app'
    metrics_path: '/Foyer/actuator/prometheus'
    static_configs:
      - targets: ['myapp:8086']
